# Scraping the net for NBA Data using BeautifulSoup

In [1]:
years = list(range (1991,2021))

In [6]:
url_start = "https://www.basketball-reference.com/awards/awards_{}.html"
import requests

In [7]:
import requests
for year in years:
    url=url_start.format(year)
    data=requests.get(url)
    
    with open("mvp/{}.html".format(year),"w+",encoding="utf-8") as f:
        f.write(data.text)

In [8]:
from bs4 import BeautifulSoup

In [65]:
soup= BeautifulSoup(page,"html.parser")

In [68]:
import pandas as pd

# Importing MVP data

In [69]:
dfs=[]
for year in years:
    with open("mvp/{}.html".format(year),encoding="utf-8") as f:
        page=f.read()
    soup= BeautifulSoup(page,"html.parser")
    soup.find('tr',class_="over_header").decompose()
    mvp_table=soup.find(id="mvp")
    mvp=pd.read_html(str(mvp_table))[0]
    mvp["Year"]=year
    dfs.append(mvp)

In [29]:
dfs[3]

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
0,1,Hakeem Olajuwon,31,HOU,66.0,889.0,1010,0.880,80,41.0,...,11.9,3.6,1.6,3.7,0.528,0.421,0.716,14.3,0.210,1994
1,2,David Robinson,28,SAS,24.0,730.0,1010,0.723,80,40.5,...,10.7,4.8,1.7,3.3,0.507,0.345,0.749,20.0,0.296,1994
2,3,Scottie Pippen,28,CHI,7.0,390.0,1010,0.386,72,38.3,...,8.7,5.6,2.9,0.8,0.491,0.320,0.660,11.2,0.194,1994
3,4,Shaquille O'Neal,21,ORL,3.0,289.0,1010,0.286,81,39.8,...,13.2,2.4,0.9,2.9,0.599,0.000,0.554,16.9,0.252,1994
4,5,Patrick Ewing,31,NYK,1.0,255.0,1010,0.252,79,37.6,...,11.2,2.3,1.1,2.7,0.496,0.286,0.765,13.1,0.211,1994
5,6,Gary Payton,25,SEA,0.0,20.0,1010,0.020,82,35.1,...,3.3,6.0,2.3,0.2,0.504,0.278,0.595,9.3,0.155,1994
6,7T,Shawn Kemp,24,SEA,0.0,17.0,1010,0.017,79,32.9,...,10.8,2.6,1.8,2.1,0.538,0.250,0.741,11.7,0.216,1994
7,7T,Karl Malone,30,UTA,0.0,17.0,1010,0.017,82,40.6,...,11.5,4.0,1.5,1.5,0.497,0.250,0.694,13.4,0.193,1994
8,9,Mark Price,29,CLE,0.0,7.0,1010,0.007,76,31.4,...,3.0,7.8,1.4,0.1,0.478,0.397,0.888,10.0,0.201,1994
9,10,Charles Barkley,30,PHO,0.0,5.0,1010,0.005,65,35.4,...,11.2,4.6,1.6,0.6,0.495,0.270,0.704,8.8,0.185,1994
10,11T,Mookie Blaylock,26,ATL,0.0,1.0,1010,0.001,81,36.0,...,5.2,9.7,2.6,0.5,0.411,0.334,0.730,10.2,0.168,1994
11,11T,Kevin Johnson,27,PHO,0.0,1.0,1010,0.001,67,36.6,...,2.5,9.5,1.9,0.1,0.487,0.222,0.819,8.7,0.170,1994
12,11T,Dennis Rodman,32,SAS,0.0,1.0,1010,0.001,79,37.8,...,17.3,2.3,0.7,0.4,0.534,0.208,0.520,8.7,0.140,1994
13,11T,Latrell Sprewell,23,GSW,0.0,1.0,1010,0.001,82,43.1,...,4.9,4.7,2.2,0.9,0.433,0.361,0.774,8.0,0.108,1994
14,11T,John Stockton,31,UTA,0.0,1.0,1010,0.001,82,36.2,...,3.1,12.6,2.4,0.3,0.528,0.322,0.805,13.2,0.214,1994
15,11T,Dominique Wilkins,34,TOT,0.0,1.0,1010,0.001,74,35.6,...,6.5,2.3,1.2,0.4,0.440,0.288,0.847,8.4,0.153,1994
16,11T,Kevin Willis,31,ATL,0.0,1.0,1010,0.001,80,35.8,...,12.0,1.9,1.0,0.5,0.499,0.375,0.713,10.2,0.170,1994

In [70]:
mvps=pd.concat(dfs)

In [71]:
mvps.tail()

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
7,8,Damian Lillard,29,POR,0.0,23.0,1010,0.023,66,37.5,...,4.3,8.0,1.1,0.3,0.463,0.401,0.888,11.6,0.225,2020
8,9,Nikola Jokić,24,DEN,0.0,18.0,1010,0.018,73,32.0,...,9.7,7.0,1.2,0.6,0.528,0.314,0.817,9.8,0.202,2020
9,10,Pascal Siakam,25,TOR,0.0,17.0,1010,0.017,60,35.2,...,7.3,3.5,1.0,0.9,0.453,0.359,0.792,5.4,0.123,2020
10,11,Jimmy Butler,30,MIA,0.0,9.0,1010,0.009,58,33.8,...,6.7,6.0,1.8,0.6,0.455,0.244,0.834,9.0,0.221,2020
11,12,Jayson Tatum,21,BOS,0.0,1.0,1010,0.001,66,34.3,...,7.0,3.0,1.4,0.9,0.450,0.403,0.812,6.9,0.146,2020

# Saving the scraped data onto a new .csv file

In [72]:
mvps.to_csv("mvps.csv")

# Using selenium to scrape data from a webpage which uses JavaScript

In [78]:
from selenium import webdriver

In [79]:
driver = webdriver.Chrome()

## Importing NBA player stats

In [25]:
#DONT RUN AGAIN 
for year in years:
    url=player_stats_url.format(2023)
    driver.get(url)
    driver.execute_script("window.scrollTo(1,10000)")
    time.sleep(2)
    html=driver.page_source
    with open("player/{}.html".format(year),"w+",encoding="utf-8") as f:
        f.write(html)

In [41]:
soup= BeautifulSoup(page,"html.parser")

# Getting the data from the html files

In [82]:
dfs=[]
for year in years:
    with open("player/{}.html".format(year),encoding="utf-8") as f:
        page=f.read()
    soup= BeautifulSoup(page,"html.parser")
    soup.find('tr',class_="thead").decompose()
    player_table=soup.find(id="per_game_stats")
    player=pd.read_html(str(player_table))[0]
    player["Year"]=year
    dfs.append(player)

In [83]:
players=pd.concat(dfs)

In [75]:
players

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,1,Alaa Abdelnaby,PF,22,POR,43,0,6.7,1.3,2.7,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,1991
1,2,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,22.5,6.2,15.1,...,0.5,1.3,1.8,3.1,0.8,0.1,1.6,2.2,14.1,1991
2,3,Mark Acres,C,28,ORL,68,0,19.3,1.6,3.1,...,2.1,3.2,5.3,0.4,0.4,0.4,0.6,3.2,4.2,1991
3,4,Michael Adams,PG,28,DEN,66,66,35.5,8.5,21.5,...,0.9,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5,1991
4,5,Mark Aguirre,SF,31,DET,78,13,25.7,5.4,11.7,...,1.7,3.1,4.8,1.8,0.6,0.3,1.6,2.7,14.2,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
671,525,Trae Young,PG,21,ATL,60,60,35.3,9.1,20.8,...,0.5,3.7,4.3,9.3,1.1,0.1,4.8,1.7,29.6,2020
672,526,Cody Zeller,C,27,CHO,58,39,23.1,4.3,8.3,...,2.8,4.3,7.1,1.5,0.7,0.4,1.3,2.4,11.1,2020
673,527,Tyler Zeller,C,30,SAS,2,0,2.0,0.5,2.0,...,1.5,0.5,2.0,0.0,0.0,0.0,0.0,0.0,1.0,2020
674,528,Ante Žižić,C,23,CLE,22,0,10.0,1.9,3.3,...,0.8,2.2,3.0,0.3,0.3,0.2,0.5,1.2,4.4,2020
675,529,Ivica Zubac,C,22,LAC,72,70,18.4,3.3,5.3,...,2.7,4.8,7.5,1.1,0.2,0.9,0.8,2.3,8.3,2020

# Saving the data into .csv file

In [84]:
players.to_csv("players.csv")

# Getting the Nba teams data using BeautifulSoup

In [10]:
team_stats_url="https://www.basketball-reference.com/leagues/NBA_{}_standings.html"

In [15]:
for year in years:
    url=team_stats_url.format(year)
    
    data=requests.get(url)
    
    with open("team/{}.html".format(year),"w+",encoding="utf-8") as f:
        f.write(data.text)

# Importing the data from the saved .html files

In [89]:
dfs=[]
for year in years:
    with open("team/{}.html".format(year),encoding="utf-8") as f:
        page=f.read()
        soup= BeautifulSoup(page,"html.parser")
        soup.find('tr',class_="thead").decompose()
        team_table=soup.find(id="divs_standings_E")
        team=pd.read_html(str(team_table))[0]
        team["Year"]=year
        team["Team"]=team["Eastern Conference"]
        del team["Eastern Conference"]
        dfs.append(team)
        
        soup= BeautifulSoup(page,"html.parser")
        soup.find('tr',class_="thead").decompose()
        team_table=soup.find(id="divs_standings_W")
        team=pd.read_html(str(team_table))[0]
        team["Year"]=year
        team["Team"]=team["Western Conference"]
        del team["Western Conference"]
        dfs.append(team)

In [90]:
teams=pd.concat(dfs)

In [91]:
teams

     W   L  W/L%    GB   PS/G   PA/G    SRS  Year                  Team
0   56  26  .683     —  111.5  105.7   5.22  1991       Boston Celtics*
1   44  38  .537  12.0  105.4  105.6  -0.39  1991   Philadelphia 76ers*
2   39  43  .476  17.0  103.1  103.3  -0.43  1991      New York Knicks*
3   30  52  .366  26.0  101.4  106.4  -4.84  1991    Washington Bullets
4   26  56  .317  30.0  102.9  107.5  -4.53  1991       New Jersey Nets
..  ..  ..   ...   ...    ...    ...    ...   ...                   ...
13  44  28  .611     —  117.8  114.8   3.13  2020      Houston Rockets*
14  43  32  .573   2.5  117.0  112.1   4.87  2020     Dallas Mavericks*
15  34  39  .466  10.5  112.6  113.7  -0.91  2020     Memphis Grizzlies
16  32  39  .451  11.5  114.1  115.2  -0.65  2020     San Antonio Spurs
17  30  42  .417  14.0  115.8  117.1  -0.55  2020  New Orleans Pelicans

[998 rows x 9 columns]

# Saving the data into a new .csv file

In [92]:
teams.to_csv("teams.csv")